name: Page Fetching

on: [ push ]

jobs:
  page-fetching:
    runs-on: [ ubuntu-latest, windows-latest, macos-latest ]

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install

      - name: Run Page Fetching
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
        run: node index.js